### ISSUE TITLE
一部設定が保存されていない

### ISSUE THREAD

**Issue by k725** [mohemohe/ImageViewer#29]
develop版で確認

"30秒動画の警告～" がONにして保存して起動し直すとOFFになってます

**Comment by k725** [comment]
OS再起動したらなんか治ってました なのでマイクロソフトはクソ

**Comment by mohemohe** [comment]
XMLのシリアライズには成功しても、デシリアライズに失敗する環境があることを確認しました
正常に保存されますが、起動時の読み込みに失敗して、デフォルトの設定になってしまうことがあるようです

**Comment by mohemohe** [comment]
やはり一部の環境で設定が保存されていない
今度はシリアライズ後のFileStreamへの書き込みに失敗してる気がするんだけど、Exceptionを吐かないので何が原因なのか分からん
Microsoftがすべて悪い
